spring:
  application:
    name: ApiGetway
  cloud:
    gateway:
      mvc:
        routes:
         - id: ARTICLE-MANAGER-SERVICE
           uri: lb://ArticleMgr
           predicates:
             - Path=/article/**
         - id: MEMBER-AUTHENTICAT-SERVICE
           uri: lb://SecurityAndMemberMgr
           predicates: 
             - Path=/member/**, /auth/**
         - id: DAO-SERVICE
           uri: lb://DAO
           predicates:
              - Path=/dao**

eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      instance:
        preferIpAddress: true		

