name: Deploy to AWS ECS

on:
  push:
    branches:
      - main  # Déclenche l'action quand du code est poussé sur la branche main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY_URI }}

      - name: Pull RabbitMQ from Docker Hub
        run: docker pull rabbitmq:latest

      - name: Tag image for ACR
        run: docker tag rabbitmq:latest ${{ secrets.ECR_REPOSITORY_URI }}:latest

      - name: Pusher l'image dans ECR
        run: docker push ${{ secrets.ECR_REPOSITORY_URI }}:latest

      
